spring.application.name=sa-project

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/Foam
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.security.user.name=user
spring.security.user.password=pass123

spring.jpa.hibernate.ddl-auto=update